version: '3'

services:
  app:
    build: .
    volumes:
      - .:/app:cached
    ports:
      - 8000:8000
    command: ["wait-for", "db:3306", "--", "wait-for", "redis:6379", "--", "air"]
    depends_on:
      - db
      - redis
  db:
    image: mariadb:focal
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=bojgarden
    ports:
      - 3306:3306
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
